version: '3.9'

volumes:
  mysql-data:

services:
  # Reverse Proxy
  # nginx:
  #   container_name: nameko-nginx
  #   image: nginx:1.23.0-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  nginx:
    container_name: nameko-microservices-nginx
    # image: nginx:1.23.0-alpine
    image: owasp/modsecurity-crs:3-nginx
    ports:
      - "80:80"
    volumes:
     - ./nginx-modsecurity/nginx.conf:/etc/nginx/templates/nginx.conf.template:rw
  
  # AMQP
  rabbitmq:
    container_name: nameko-microservices-rabbitmq
    image: rabbitmq:3.10-management-alpine
    restart: always
    ports:
      - 5672:5672
  
  # Data Storage
  mysql:
    container_name: nameko-microservices-mysql
    image: mysql:5.7.38-debian
    command: 
      --init-file /data/application/init.sql 
      --default-authentication-plugin=mysql_native_password
    volumes:
      - .mysql-data:/var/lib/mysql
      - ./sql/init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: change_me
    ports:
      - 3306:3306
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  
  # Database Admin
  phpmyadmin:
    container_name: nameko-microservices-phpmyadmin
    image: nameko-microservices-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
  
  redis:
    container_name: nameko-microservices-redis
    image: redis:7.0.2-alpine3.16
    restart: always
    ports:
      - 6379:6379

  # front end
  web-ui-service:
    container_name: nameko-microservices-web-ui-service
    build: ./services/web-ui/
    ports:
      - 8020:8020
    volumes:
      - ./services/web-ui:/var/www/html
    depends_on:
      - nginx

  user-service:
    container_name: nameko-microservices-user-service
    image: nameko-microservices-user-service
    volumes:
      - ./services/user:/data/application
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
      - DB_PASS=change_me
      - DB_NAME=nameko
      - DB_USER=root
  
  user-gateway:
    container_name: nameko-microservices-user-gateway
    image: nameko-microservices-user-gateway
    volumes:
      - ./services/user:/data/application
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  library-service:
    container_name: nameko-microservices-library-service
    image: nameko-microservices-library-service
    volumes:
      - ./services/library:/data/application
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
      - DB_PASS=change_me
      - DB_NAME=nameko
      - DB_USER=root
  
  library-gateway:
    container_name: nameko-microservices-library-gateway
    image: nameko-microservices-library-gateway
    volumes:
      - ./services/library:/data/application
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  user-library-service:
    container_name: nameko-microservices-user-library-service
    image: nameko-microservices-user-library-service
    volumes:
      - ./services/user-library:/data/application
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=mysql
      - DB_PASS=change_me
      - DB_NAME=nameko
      - DB_USER=root
  
  user-library-gateway:
    container_name: nameko-microservices-user-library-gateway
    image: nameko-microservices-user-library-gateway
    volumes:
      - ./services/user-library:/data/application
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=redis
      - REDIS_PORT=6379